import actionTypeCreator, { SYNC, ASYNC } from 'redux-action-types-creator';

const actions = actionTypeCreator('AMLC');

export default actions({
	AML: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	CASES: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	CUSTOMERS: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	FACT: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	MEMBER: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	RISK: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},

	USERS: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	},
	USERTYPE: {
		FETCH: ASYNC,
		SETFORM: ASYNC,
		CREATE: ASYNC,
		UPDATE: ASYNC,
		DELETE: ASYNC,
		MODAL: SYNC
	}
});
